version: "3.8"
services:
  web-info:
    image: siarheikazei/web-info
    networks:
      - net2
    environment:
      - RAND_HOST=rand-info
      - RAND_PORT=8080
    ports:
      - target: 8080
        published: 80
  rand-info:
    image: siarheikazei/rand-info
    networks:
      - net2
networks:
  net2: